# SQLite version 3.x
development:
  adapter: mysql
  encoding: utf8
  database: mobile_ruby_prod
  username: root
  password:
  host: localhost
test:
  adapter: mysql
  encoding: utf8
  database: mobile_ruby_text
  username: root
  password:
  host: localhost
production:
  adapter: mysql
  encoding: utf8
  database: mobile_ruby_production
  username: root
  password:
  host: localhost
